### ISSUE TITLE
这代码是你写的吗

### ISSUE THREAD

**Issue by SimplyY** [AnkleLiu/Demos#1]
![image](https://user-images.githubusercontent.com/8455579/40152880-bbb6b71a-59b9-11e8-86e0-ef6f87338031.png)

**Comment by SimplyY** [comment]
其实还是比较难分辨到底是不是你自己写的，

我先说一点，commit 记录实在是太粗糙了，真正的 git 工作流不是项目写完才 push，给你看一个 real repo 的 commit  https://github.com/expressjs/express/commits/master

**Comment by AnkleLiu** [comment]
@SimplyY 
这是一门关于 Redux 的课程，初始代码是图片里这个老师准备的，完整代码是我一边上课一边自己敲的。
commit 确实很粗糙，当时是找工作之前一起 push 的，平时就放在硬盘里了。
